### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by bandhacker** [validator/validator#761]
I get the warning "Stray start tag script." The end of the source code displayed is as follows, but this is not the end of the actual source code.

<script>
    $('.wrapper').animate({ opacity: 1.0 }, 1200);

    function openOptimal (){
        window.open(

**Comment by sideshowbarker** [comment]
You’ll need to provide a document/URL I can test with to try to reproduce the problem.

**Comment by bandhacker** [comment]
bandhacker.com

**Comment by nschonni** [comment]
Your script tag is outside the HTML element entirely

**Comment by taftsa** [comment]
Fixed that and now it's pulling the rest of the code, but it's still returning the same error even thougthere is a close tag.

**Comment by nschonni** [comment]
it needs to be in the body or head https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

**Comment by taftsa** [comment]
Got it. Thanks!

**Comment by sideshowbarker** [comment]
So yeah, as @nschonni pointed out, the document had a serious markup error. But even so, the checker should have still shown the entire source instead of truncating it.
